server:
  port: 8989
  servlet:
    context-path: /tryDocker

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///clouddb2.0?useSSL=false
    url: jdbc:mysql://localhost:3306/books?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 2640
mybatis:
  type-aliases-package: com.example.trydocker.entity
  mapper-locations: classpath:com/example/trydocker/mapper/*.xml
